[MediaInlineQueueRowStyle]
H=(18*#Scale#)
Group=QueueRows
Hidden=1

[MeterQueueRow1]
Meter=String
MeterStyle=StyleLabel|MediaInlineQueueRowStyle
Y=#Inset#
Text=

[MeterQueueRow2]
Meter=String
MeterStyle=StyleLabel|MediaInlineQueueRowStyle
Y=#Inset#
Text=

[MeterQueueRow3]
Meter=String
MeterStyle=StyleLabel|MediaInlineQueueRowStyle
Y=#Inset#
Text=

[MeterQueueRow4]
Meter=String
MeterStyle=StyleLabel|MediaInlineQueueRowStyle
Y=#Inset#
Text=

[MeterQueueRow5]
Meter=String
MeterStyle=StyleLabel|MediaInlineQueueRowStyle
Y=#Inset#
Text=
